Script started on Sat 08 Sep 2018 02:47:02 AM CDT
]0;thatchdawg@thatchdawg:~/cs161[?1034h[thatchdawg@thatchdawg cs161]$ cd root/
]0;thatchdawg@thatchdawg:~/cs161/root[thatchdawg@thatchdawg root]$ ./sys161 kernel
sys161: System/161 release 1.14, compiled Sep  8 2018 02:17:33

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p . /sbin/poweroff <return>
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 437895286 cycles (5064367k, 18u, 432830901i)
sys161: 2394 irqs 6 exns 0r/0w disk 28r/671w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 17.530319 seconds (24.9793 mhz)
sys161: Elapsed virtual time: 17.515811440 seconds (25 mhz)
]0;thatchdawg@thatchdawg:~/cs161/root[thatchdawg@thatchdawg root]$ exit
exit

Script done on Sat 08 Sep 2018 02:47:35 AM CDT
