Script started on Tue 28 Aug 2018 11:13:17 PM CDT
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[?1034h[thatchdawg@thatchdawg Project01]$ man script
[?1049h[?1h=SCRIPT(1)                 BSD General Commands Manual                SCRIPT(1)

[1mNAME[0m
     [1mscript[0m - make typescript of terminal session

[1mSYNOPSIS[0m
     [1mscript[0m [[1m-a[0m] [[1m-c[0m [4mCOMMAND[24m] [[1m-f[0m] [[1m-q[0m] [[1m-t[0m] [[4mfile[24m]

[1mDESCRIPTION[0m
     [1mScript[0m makes a typescript of everything printed on your terminal.  It is
     useful for students who need a hardcopy record of an interactive session
     as proof of an assignment, as the typescript file can be printed out
     later with lpr(1).

     If the argument [4mfile[24m is given, [1mscript[0m saves all dialogue in [4mfile[24m.  If no
     file name is given, the typescript is saved in the file [4mtypescript[24m.

     Options:

     [1m-a[0m      Append the output to [4mfile[24m or [4mtypescript[24m, retaining the prior con-
             tents.

     [1m-c[0m [4mCOMMAND[24m
:[K[K[?1l>[?1049l]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ cd ../
]0;thatchdawg@thatchdawg:~/Desktop/Projects[thatchdawg@thatchdawg Projects]$ cd Project01/
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ pwd
/home/thatchdawg/Desktop/Projects/Project01
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ ls
changePermissions.script  commands.script  toDelete.script
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ mkdir to[K[KdirDelete
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ cp toDelete.script dirDelete/toDelete.script
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ cd [K[K[Kmv toDelete.script dirDelete/toDelewte[K[K[Kte2.script [A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Kt
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ cd t[Kdir[K[K[K[K[K[Kls
changePermissions.script  commands.script  [0m[01;34mdirDelete[0m
[m]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ cd dirDelete/
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01/dirDelete[thatchdawg@thatchdawg dirDelete]$ ls
toDelete2.script  toDelete.script
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01/dirDelete[thatchdawg@thatchdawg dirDelete]$ rm toDelete.script
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01/dirDelete[thatchdawg@thatchdawg dirDelete]$ rm toDelete2.script 
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01/dirDelete[thatchdawg@thatchdawg dirDelete]$ cd ../
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ ls
changePermissions.script  commands.script  [0m[01;34mdirDelete[0m
[m]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ rmdir dirDelete/
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ chmod a-w+x c[KchangePermissions.script 
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ chmod go-rw changePermissions.script 
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ clear
[H[2J]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ top
[H[2J(B[mtop - 23:16:06 up 30 min,  4 users,  load average: 0.02, 0.22, 0.16(B[m[39;49m[K
Tasks:(B[m[39;49m(B[m 122 (B[m[39;49mtotal,(B[m[39;49m(B[m   1 (B[m[39;49mrunning,(B[m[39;49m(B[m 121 (B[m[39;49msleeping,(B[m[39;49m(B[m   0 (B[m[39;49mstopped,(B[m[39;49m(B[m   0 (B[m[39;49mzombie(B[m[39;49m[K
Cpu(s):(B[m[39;49m(B[m 13.5%(B[m[39;49mus,(B[m[39;49m(B[m  2.5%(B[m[39;49msy,(B[m[39;49m(B[m  0.0%(B[m[39;49mni,(B[m[39;49m(B[m 83.5%(B[m[39;49mid,(B[m[39;49m(B[m  0.1%(B[m[39;49mwa,(B[m[39;49m(B[m  0.2%(B[m[39;49mhi,(B[m[39;49m(B[m  0.3%(B[m[39;49msi,(B[m[39;49m(B[m  0.0%(B[m[39;49mst(B[m[39;49m[K
Mem: (B[m[39;49m(B[m  8181172k (B[m[39;49mtotal,(B[m[39;49m(B[m  1632148k (B[m[39;49mused,(B[m[39;49m(B[m  6549024k (B[m[39;49mfree,(B[m[39;49m(B[m    43384k (B[m[39;49mbuffers(B[m[39;49m[K
Swap:(B[m[39;49m(B[m  5242872k (B[m[39;49mtotal,(B[m[39;49m(B[m        0k (B[m[39;49mused,(B[m[39;49m(B[m  5242872k (B[m[39;49mfree,(B[m[39;49m(B[m  1386116k (B[m[39;49mcached(B[m[39;49m[K
[6;1H
[7m  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND            (B[m[39;49m[K
(B[m(B[m 2624 thatchda  20   0  2728 1032  788 R  1.7  0.0   0:00.07 top                (B[m[39;49m
(B[m    1 root      20   0  2904 1428 1212 S  0.0  0.0   0:01.33 init               (B[m[39;49m
(B[m    2 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kthreadd           (B[m[39;49m
(B[m    3 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 migration/0        (B[m[39;49m
(B[m    4 root      20   0     0    0    0 S  0.0  0.0   0:00.21 ksoftirqd/0        (B[m[39;49m
(B[m    5 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 migration/0        (B[m[39;49m
(B[m    6 root      RT   0     0    0    0 S  0.0  0.0   0:00.03 watchdog/0         (B[m[39;49m
(B[m    7 root      20   0     0    0    0 S  0.0  0.0   0:01.78 events/0           (B[m[39;49m
(B[m    8 root      20   0     0    0    0 S  0.0  0.0   0:00.00 cgroup             (B[m[39;49m
(B[m    9 root      20   0     0    0    0 S  0.0  0.0   0:00.00 khelper            (B[m[39;49m
(B[m   10 root      20   0     0    0    0 S  0.0  0.0   0:00.00 netns              (B[m[39;49m
(B[m   11 root      20   0     0    0    0 S  0.0  0.0   0:00.00 async/mgr          (B[m[39;49m
(B[m   12 root      20   0     0    0    0 S  0.0  0.0   0:00.00 pm                 (B[m[39;49m
(B[m   13 root      20   0     0    0    0 S  0.0  0.0   0:00.01 sync_supers        (B[m[39;49m
(B[m   14 root      20   0     0    0    0 S  0.0  0.0   0:00.01 bdi-default        (B[m[39;49m
(B[m   15 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kintegrityd/0      (B[m[39;49m
(B[m   16 root      20   0     0    0    0 S  0.0  0.0   0:00.49 kblockd/0          (B[m[39;49m[6;1H[K[H(B[mtop - 23:16:09 up 30 min,  4 users,  load average: 0.02, 0.21, 0.16(B[m[39;49m[K
Tasks:(B[m[39;49m(B[m 122 (B[m[39;49mtotal,(B[m[39;49m(B[m   1 (B[m[39;49mrunning,(B[m[39;49m(B[m 121 (B[m[39;49msleeping,(B[m[39;49m(B[m   0 (B[m[39;49mstopped,(B[m[39;49m(B[m   0 (B[m[39;49mzombie(B[m[39;49m[K
Cpu(s):(B[m[39;49m(B[m  1.0%(B[m[39;49mus,(B[m[39;49m(B[m  1.0%(B[m[39;49msy,(B[m[39;49m(B[m  0.0%(B[m[39;49mni,(B[m[39;49m(B[m 98.0%(B[m[39;49mid,(B[m[39;49m(B[m  0.0%(B[m[39;49mwa,(B[m[39;49m(B[m  0.0%(B[m[39;49mhi,(B[m[39;49m(B[m  0.0%(B[m[39;49msi,(B[m[39;49m(B[m  0.0%(B[m[39;49mst(B[m[39;49m[K
Mem: (B[m[39;49m(B[m  8181172k (B[m[39;49mtotal,(B[m[39;49m(B[m  1632404k (B[m[39;49mused,(B[m[39;49m(B[m  6548768k (B[m[39;49mfree,(B[m[39;49m(B[m    43392k (B[m[39;49mbuffers(B[m[39;49m[K
Swap:(B[m[39;49m(B[m  5242872k (B[m[39;49mtotal,(B[m[39;49m(B[m        0k (B[m[39;49mused,(B[m[39;49m(B[m  5242872k (B[m[39;49mfree,(B[m[39;49m(B[m  1386124k (B[m[39;49mcached(B[m[39;49m[K
[6;1H
[7m  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND            (B[m[39;49m[K
(B[m(B[m 2624 thatchda  20   0  2700 1136  888 R  1.3  0.0   0:00.11 top                (B[m[39;49m
(B[m  143 root      20   0     0    0    0 S  0.3  0.0   0:01.38 scsi_eh_1          (B[m[39;49m
(B[m 1603 root      20   0 81000  24m  10m S  0.3  0.3   0:22.57 Xorg               (B[m[39;49m
(B[m    1 root      20   0  2904 1428 1212 S  0.0  0.0   0:01.33 init               (B[m[39;49m
(B[m    2 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kthreadd           (B[m[39;49m
(B[m    3 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 migration/0        (B[m[39;49m
(B[m    4 root      20   0     0    0    0 S  0.0  0.0   0:00.21 ksoftirqd/0        (B[m[39;49m
(B[m    5 root      RT   0     0    0    0 S  0.0  0.0   0:00.00 migration/0        (B[m[39;49m
(B[m    6 root      RT   0     0    0    0 S  0.0  0.0   0:00.03 watchdog/0         (B[m[39;49m
(B[m    7 root      20   0     0    0    0 S  0.0  0.0   0:01.78 events/0           (B[m[39;49m
(B[m    8 root      20   0     0    0    0 S  0.0  0.0   0:00.00 cgroup             (B[m[39;49m
(B[m    9 root      20   0     0    0    0 S  0.0  0.0   0:00.00 khelper            (B[m[39;49m
(B[m   10 root      20   0     0    0    0 S  0.0  0.0   0:00.00 netns              (B[m[39;49m
(B[m   11 root      20   0     0    0    0 S  0.0  0.0   0:00.00 async/mgr          (B[m[39;49m
(B[m   12 root      20   0     0    0    0 S  0.0  0.0   0:00.00 pm                 (B[m[39;49m
(B[m   13 root      20   0     0    0    0 S  0.0  0.0   0:00.01 sync_supers        (B[m[39;49m
(B[m   14 root      20   0     0    0    0 S  0.0  0.0   0:00.01 bdi-default        (B[m[39;49m[6;1H[K[25;1H[?12l[?25h
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ who
thatchdawg tty1         2018-08-28 22:47 (:0)
thatchdawg pts/0        2018-08-28 22:48 (:0.0)
thatchdawg pts/1        2018-08-28 23:08 (:0.0)
thatchdawg pts/2        2018-08-28 23:13
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ nproc
1
]0;thatchdawg@thatchdawg:~/Desktop/Projects/Project01[thatchdawg@thatchdawg Project01]$ exit
exit

Script done on Tue 28 Aug 2018 11:16:18 PM CDT
